const data = {
    "jp":{
        "wedding":"ミン　クォン　&　ホアイ　トゥーン",
        "content":"謹啓<br><br>皆様におかれましては<br>ますますご清祥のこととお慶び申し上げます<br><br>このたび　私たちは結婚をすることになりました<br>つきましては　日頃お世話になっております皆様に<br>感謝を込めて　ささやかな小宴を催したく存じます<br><br>ご多用中　誠に恐縮ではございますが<br>ぜひご出席をいただきたく　ご案内申し上げます<br><br>謹白",
        "date": "日付：2023年01月02日(月)",
        "checkin":"挙式：12時00分(受付 11時30分)",
        "party":"披露宴：13時00分(受付 12時30分)",
        "Addr":"場所: LONG BIEN PALACE",
        "deadline":"お手数ではございますが<br>ご都合の程を<span class=\"limit_date\">07月10日</span>迄に<br>ご一報賜りますようお願い申し上げます",
        "button":"招待状に回答する",
        "need":"*は必須項目です",
        "choise":"いずれかをお選びください",
        "accepts":"ご出席",
        "accepts_span":"<br/>ご出席",
        "declines":"ご欠席",
        "declines_span":"<br/>ご欠席",
        "name":"お名前*",
        "name2":"お名前",
        "Message":"メッセージ",
        "Messageinf":"ご自由にご記入ください",
        "buttonans":"確認する",
        "errorlist":"お名前ドロップダウンリストの項目からご選択ください。",
        "erroraccept":"出席/欠席の返信をご選択ください。",
        "back":" 戻る",
        "conffirm":"入力確認画面",
        "acceptdecline":"ご出席/ご欠席",
        "btnconf":"回答する",
        "edit":" 修正",
        "thanks":"ご回答ありがとうございました",
        "backtop":"招待状トップへ"
    },
    "vn":{
        "wedding":"Minh Quân & Hoài Thương",
        "content":"Hé Lu mọi người<br><br>Cuối cùng sau 4 năm dài đằng đẵng tìm hiểu nhau.<br> Cũng như được sự đồng ý của 2 bên gia đình.<br>Bọn em đã quyết định chia tay với cuộc sống độc thân.<br>Nhân ngày lành tháng tốt mở một bữa tiệc nhỏ để mọi người có thể đến chung vui.<br>Rất mong sự có mặt của mọi người hôm đó!!<br><br>",
        "date": "Thời gian：Ngày 10/7/2022 (Chủ Nhật)",
        "checkin":"Đón Khách：11 giờ 00",
        "party":"Nhập Tiệc：12 giờ 00",
        "Addr":"Địa Chỉ: TRUNG TÂM HỘI NGHỊ TIỆC CƯỚI LONG BIÊN PALACE ",
        "deadline":"Để chuẩn bị tốt cho bữa tiệc.<br>Trước <span class=\"limit_date\">Ngày 10 Tháng 12 </span>Mọi người vui lòng xác nhận có tham gia hay không ở bên dưới giúp bọn em",
        "button":"XÁC NHẬN THAM GIA",
        "need":"*là những phần bắt buộc",
        "choise":"Chọn 1 trong 2",
        "accepts":"Tham gia",
        "accepts_span":"<br/>Tham gia",
        "declines":"Nhất định tham gia",
        "declines_span":"<br/>Nhất định tham gia",
        "name":"Nhập tên và chọn *",
        "name2":"Tên",
        "Message":"Tin nhắn",
        "Messageinf":"Gửi lời chúc đến hai đứa",
        "buttonans":"XÁC NHẬN",
        "errorlist":"Vui lòng chọn tên trong danh sách có sẵn.",
        "erroraccept":"Vui lòng chọn trả lời tham gia hoặc nhất định tham gia giúp bọn em.",
        "back":" QUAY LẠI",
        "conffirm":"XÁC NHẬN NỘI DUNG ĐÃ NHẬP",
        "acceptdecline":"Trả lời",
        "btnconf":"GỬI",
        "edit":" CHỈNH SỬA",
        "thanks":"Cảm ơn đã xác nhận!",
        "backtop":"Màn hình chính"
    }
}